// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FadeController from "./fade_controller"
application.register("fade", FadeController)

import GiftLoadingController from "./gift_loading_controller"
application.register("gift-loading", GiftLoadingController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
